### PR TITLE
added omega_h detection

### PR DESCRIPTION
**Pull request by junghans**
This change is [Reviewable](https://reviewable.io/reviews/quinoacomputing/cmake-modules/21)

### CODE REVIEW

**Comment by jbakosi** [comment]
Looks good, thanks. Please see minor comment below. Good to go.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @junghans)

---

*[FindOmega_h.cmake, line 4 at r1](https://reviewable.io/reviews/quinoacomputing/cmake-modules/21#-LFPg2YE3SToIZMGnzoC:-LFPg2YE3SToIZMGnzoD:bh4291u) ([raw file](https://github.com/quinoacomputing/cmake-modules/blob/8a20499b170db313a96e36c7835adb361d417597/FindOmega_h.cmake#L4)):*
> ```CMake
> #
> # \file      cmake/FindOmega_h.cmake
> # \copyright 2018, Los Alamos National Security, LLC.
> ```

No t really a big deal, but I think if you use `2016-2018` instead of only `2018`, [quinoa::src/script/update_copyright.sh](https://github.com/quinoacomputing/quinoa/blob/master/script/update_copyright.sh) will catch it next time.

---

*[TPLs.cmake, line 164 at r1](https://reviewable.io/reviews/quinoacomputing/cmake-modules/21#-LFPfk0W0zgfkXZzBpB4:-LFPfk0W0zgfkXZzBpB5:boqa7wx) ([raw file](https://github.com/quinoacomputing/cmake-modules/blob/8a20499b170db313a96e36c7835adb361d417597/TPLs.cmake#L164)):*
> ```CMake
> find_package(Omega_h)
> if(OMEGA_H_FOUND)
>   set(HAS_OMEGA_H true)  # will become compiler define in Main/QuinoaConfig.h
> ```

Sounds good! Let's keep it optional with a compiler define.

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/cmake-modules/21#-:-LFPh3bU7PrKNjbuMmHo:b3vjpg3)*

**Comment by jbakosi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @junghans)

---



*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/cmake-modules/21#-:-LFSvm-l3SdXxPYHmQQh:bnfp4nl)*

**Review by jbakosi — APPROVED** [review]
LGTM. Please merge and don't forget to sign.

**Comment by junghans** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @jbakosi)

---

*[FindOmega_h.cmake, line 4 at r1](https://reviewable.io/reviews/quinoacomputing/cmake-modules/21#-LFPg2YE3SToIZMGnzoC:-LG1DZoz7RyzM6WLXjje:b-896fix) ([raw file](https://github.com/quinoacomputing/cmake-modules/blob/8a20499b170db313a96e36c7835adb361d417597/FindOmega_h.cmake#L4)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

No t really a big deal, but I think if you use `2016-2018` instead of only `2018`, [quinoa::src/script/update_copyright.sh](https://github.com/quinoacomputing/quinoa/blob/master/script/update_copyright.sh) will catch it next time.
</blockquote></details>

Done.

---

*[TPLs.cmake, line 164 at r1](https://reviewable.io/reviews/quinoacomputing/cmake-modules/21#-LFPfk0W0zgfkXZzBpB4:-LG1DhHc21J_38yDjcAp:b-896fix) ([raw file](https://github.com/quinoacomputing/cmake-modules/blob/8a20499b170db313a96e36c7835adb361d417597/TPLs.cmake#L164)):*
<details><summary><i>Previously, jbakosi (Jozsef Bakosi) wrote…</i></summary><blockquote>

Sounds good! Let's keep it optional with a compiler define.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/quinoacomputing/cmake-modules/21)*

**Pull request merged**
